import RaceIcon from "@assets/icons/RaceIcon";
import SoccerIcon from "@assets/icons/SoccerIcon";
import {
  Rocket,
  Gamepad,
  Users,
  Sword,
  Globe,
  Target,
  Gamepad2,
  AlertTriangle,
  SquareDashed,
  LayoutDashboard,
  GamepadDirectional,
} from "lucide-react";

export const genresOptions = [
  { id: "adventure", label: "Aventura", icon: <Gamepad2 size={16} /> },
  { id: "action", label: "Ação", icon: <Rocket size={16} /> },
  { id: "racing", label: "Corrida", icon: <RaceIcon size={16} /> },
  { id: "sports", label: "Esportes", icon: <SoccerIcon size={16} /> },
  { id: "strategy", label: "Estratégia", icon: <Users size={16} /> },
  { id: "indie", label: "Indie", icon: <Gamepad size={16} /> },
  { id: "mmo", label: "MMO", icon: <Globe size={16} /> },
  { id: "shooter", label: "Shooter", icon: <Target size={16} /> },
  { id: "mmorpg", label: "RPG", icon: <Sword size={16} /> },
  { id: "moba", label: "MOBA", icon: <Users size={16} /> },
  { id: "social", label: "Social", icon: <Users size={16} /> },
  { id: "sandbox", label: "Sandbox", icon: <Gamepad2 size={16} /> },
  { id: "open-world", label: "Mundo Aberto", icon: <Globe size={16} /> },
  { id: "survival", label: "Sobrevivência", icon: <Target size={16} /> },
  { id: "pvp", label: "Jogador contra Jogador", icon: <Users size={16} /> },
  {
    id: "pve",
    label: "Jogador contra Environment",
    icon: <Target size={16} />,
  },
  { id: "pixel", label: "Pixel Art", icon: <SquareDashed size={16} /> },
  { id: "voxel", label: "Voxel Art", icon: <LayoutDashboard size={16} /> },
  { id: "zombie", label: "Zumbi", icon: <GamepadDirectional size={16} /> },
  { id: "turn-based", label: "Baseado em Turnos", icon: <Target size={16} /> },
  { id: "first-person", label: "Primeira Pessoa", icon: <Target size={16} /> },
  { id: "third-person", label: "Terceira Pessoa", icon: <Target size={16} /> },
  { id: "top-down", label: "Visão Superior", icon: <Target size={16} /> },
  { id: "tank", label: "Tanque", icon: <Target size={16} /> },
  { id: "space", label: "Espaço", icon: <Rocket size={16} /> },
  { id: "sailing", label: "Navegação", icon: <Globe size={16} /> },
  {
    id: "side-scroller",
    label: "Scroller Lateral",
    icon: <Gamepad2 size={16} />,
  },
  { id: "superhero", label: "Super-Herói", icon: <Sword size={16} /> },
  {
    id: "permadeath",
    label: "Morte Permanente",
    icon: <AlertTriangle size={16} />,
  },
];
